MangoInstantMessenger/MangoMessengerAPI

MangoAPI.BusinessLogic/ApiCommands/KeyExchange/OpenSslConfirmKeyExchangeCommandValidator.cs
MangoAPI.BusinessLogic/ApiCommands/KeyExchange/OpenSslCreateDiffieHellmanParameterCommand.cs
MangoAPI.BusinessLogic/ApiCommands/KeyExchange/OpenSslCreateDiffieHellmanParameterCommandHandler.cs
MangoAPI.BusinessLogic/ApiCommands/KeyExchange/OpenSslCreateDiffieHellmanParameterCommandValidator.cs
MangoAPI.BusinessLogic/ApiCommands/KeyExchange/OpenSslCreateDiffieHellmanParameterResponse.cs
MangoAPI.BusinessLogic/ApiCommands/KeyExchange/OpenSslCreateKeyExchangeCommandValidator.cs
MangoAPI.BusinessLogic/ApiQueries/KeyExchange/OpenSslDownloadPartnerPublicKeyQueryValidator.cs
MangoAPI.BusinessLogic/ApiQueries/KeyExchange/OpenSslGetKeyExchangeRequestsQuery.cs
MangoAPI.BusinessLogic/ApiQueries/KeyExchange/OpenSslGetKeyExchangeRequestsQueryHandler.cs
MangoAPI.BusinessLogic/ApiQueries/KeyExchange/OpenSslGetKeyExchangeRequestsQueryValidator.cs
MangoAPI.BusinessLogic/ApiQueries/KeyExchange/OpenSslGetKeyExchangeRequestsResponse.cs
MangoAPI.Presentation/Controllers/KeyExchangeController.cs

Add validator for each openssl command and query.

MANGO-402. Add validator for each openssl command and query.

---

MangoAPI.BusinessLogic/ApiCommands/Communities/CreateChannelCommand.cs
MangoAPI.BusinessLogic/ApiCommands/Communities/CreateChatCommand.cs
MangoAPI.DiffieHellmanConsole/Extensions/InjectionExtensions.cs
MangoAPI.DiffieHellmanConsole/OpenSslHandlers/OpenSslConfirmKeyExchangeHandler.cs
MangoAPI.DiffieHellmanConsole/OpenSslHandlers/OpenSslPrintKeyExchangesHandler.cs
MangoAPI.DiffieHellmanConsole/Program.cs
MangoAPI.DiffieHellmanConsole/Services/KeyExchangeService.cs
MangoAPI.Presentation/Controllers/CommunitiesController.cs
MangoAPI.Tests/ApiCommandsTests/CreateChannelCommandHandlerTests/CreateChannelShouldThrowCountExceed100.cs
MangoAPI.Tests/ApiCommandsTests/CreateChannelCommandHandlerTests/CreateChannelTestSuccess.cs
MangoAPI.Tests/ApiCommandsTests/CreateChatCommandHandlerTests/CreateChatShouldThrowCannotCreateSelfChat.cs
MangoAPI.Tests/ApiCommandsTests/CreateChatCommandHandlerTests/CreateChatShouldThrowUserNotFound.cs
MangoAPI.Tests/ApiCommandsTests/CreateChatCommandHandlerTests/CreateChatTestSuccess.cs

MANGO-404. Implement CLI: openssl-confirm-key-exchange REQUEST_ID, confirms a request by ID.

MANGO-404. Implement CLI: openssl-confirm-key-exchange REQUEST_ID, confirms a request by ID.

---

.github/workflows/build.yml
MangoAPI.Tests/MangoAPI.Tests.csproj

MANGO-422. Fix bug with code coverage CI CD.

MANGO-422. Fix bug with code coverage CI CD.

---

Dockerfile
MangoAPI.sln
build/azure-pipelines-deploy.yml

Merge develop into master

---

MangoAPI.Presentation/MangoAPI.Presentation.csproj
MangoAPI.Presentation/Startup.cs
MangoAPI.Presentation/appsettings.json

MANGO-440. Add application insights

MANGO-440. Add application insights

---

.github/workflows/run-sonarqube-analysis.yml
MangoAPI.sln

MANGO-449. Implement SonarQube static code analysis.

MANGO-449. Implement SonarQube static code analysis.

---

.github/workflows/run-sonarqube-analysis.yml

sonarscanner action runs on ubuntu latest

sonarscanner action runs on ubuntu latest

---

.github/workflows/azure-dev.yml

azure-dev.yml action unzip artifact step added

azure-dev.yml action unzip artifact step added

---

MangoAPI.BusinessLogic/ApiQueries/Communities/SearchCommunityQueryHandler.cs
MangoAPI.BusinessLogic/ApiQueries/Contacts/SearchContactQueryHandler.cs
MangoAPI.BusinessLogic/ApiQueries/Messages/SearchChatMessageQueryHandler.cs

MANGO-467. Fix IF-ELSE is workaround in order to complete test with in-memory database.

MANGO-467. Fix IF-ELSE is workaround in order to complete test with in-memory database.

---

.github/workflows/run-build-and-test-dotnet-angular.yml
MangoAPI.Infrastructure/Exceptions/EnvironmentVariableException.cs
MangoAPI.sln
build/docker/mssql-docker/wait_database.ps1

MANGO-466. Run integration tests on docker container in Github Actions pipeline.

MANGO-466. Run integration tests on docker container in Github Actions pipeline.

---

.github/workflows/run-openssl-dh-handshake.yml

MANGO-474. Fix OPENSSL handshake pipeline.

MANGO-474. Fix OPENSSL handshake pipeline.

---

.github/workflows/run-cng-dh-handshake.yml
CNG_DH_HANDSHAKE_TEST.ps1
MangoAPI.sln

MANGO-456. Add CNG DH handshake test to the GitHub actions pipeline.

MANGO-456. Add CNG DH handshake test to the GitHub actions pipeline.

---

README.md

MANGO-480. Update README.md Add instructions to launch Angular project.

MANGO-480. Update README.md Add instructions to launch Angular project.

---

.github/workflows/azure-dev-vm-ssh-deploy.yml
.github/workflows/azure-qa-vm-ssh-deploy.yml
.github/workflows/heroku-container-deploy.yml
.github/workflows/run-angular-sonarqube-analysis.yml
.github/workflows/run-build-and-test-dotnet-angular.yml
.github/workflows/run-cng-dh-handshake.yml
.github/workflows/run-dotnet-sonarqube-analysis.yml
.github/workflows/run-openssl-dh-handshake.yml
MangoAPI.BusinessLogic/DependencyInjection/DatabaseDependencyInjection.cs
MangoAPI.Infrastructure/Database/DesignTimeDbContextFactory.cs
MangoAPI.Infrastructure/Database/MangoDbContext.cs
MangoAPI.sln
README.md

MANGO-487. Arrange github actions to the stages, drop build artifact at the end.

MANGO-487. Arrange github actions to the stages, drop build artifact at the end.

---

.github/workflows/run-build-and-test-dotnet-angular.yml
MangoAPI.sln
run-sonarqube-dotnet.sh

MANGO-489. Exclude migrations from sonarqube scan.

MANGO-489. Exclude migrations from sonarqube scan.

---

README.md

MANGO-491. Identify the main goals of the project and what you want to achieve implementing it.

MANGO-491. Identify the main goals of the project and what you want to achieve implementing it.

---

MangoAPI.BusinessLogic/MangoAPI.BusinessLogic.csproj
MangoAPI.BusinessLogic/Models/OpenSslKeyExchangeRequest.cs
MangoAPI.BusinessLogic/Responses/ResponseBase.cs
MangoAPI.DiffieHellmanLibrary/Abstractions/BaseHandler.cs
MangoAPI.DiffieHellmanLibrary/AuthHandlers/LoginHandler.cs
MangoAPI.DiffieHellmanLibrary/AuthHandlers/RefreshTokenHandler.cs
MangoAPI.DiffieHellmanLibrary/Helpers/HttpRequestHelper.cs
MangoAPI.DiffieHellmanLibrary/Helpers/TokensHelper.cs
MangoAPI.DiffieHellmanLibrary/OpenSslHandlers/OpensslPrintKeyExchangeByIdHandler.cs

MANGO-495. Update deprecated packages SignalR.

MANGO-495. Update deprecated packages SignalR.

---

build/azure-pipelines-common.yml

MANGO-502. Run integration tests on the microsoft ms-sql database image (azure pipelines)

MANGO-502. Run integration tests on the microsoft ms-sql database image (azure pipelines)

---

MangoAPI.sln
build/azure-pipelines-common.yml
build/azure-pipelines-sonarqube.yml
build/coverage.runsettings

MANGO-503. Implement sonar validation on behalf of azure pipelines.

MANGO-503. Implement sonar validation on behalf of azure pipelines.

---

MangoAPI.Client/src/app/app-routing.module.ts
MangoAPI.Client/src/app/components/gateway/gateway.component.ts
MangoAPI.Client/src/app/services/messenger/routing.service.ts
build/azure-pipelines-common.yml

MANGO-504. Make default redirect to the chats component on the front end.

MANGO-504. Make default redirect to the chats component on the front end.

---

MangoAPI.Client/angular.json
MangoAPI.Client/src/app/components/chats/chats.component.ts
MangoAPI.Client/src/app/services/api/apiBase.service.ts
MangoAPI.Client/src/app/services/api/communities.service.ts
MangoAPI.Client/src/app/services/api/contacts.service.ts
MangoAPI.Client/src/app/services/api/documents.service.ts
MangoAPI.Client/src/app/services/api/messages.service.ts
MangoAPI.Client/src/app/services/api/password-restore.service.ts
MangoAPI.Client/src/app/services/api/session.service.ts
MangoAPI.Client/src/app/services/api/user-chats.service.ts
MangoAPI.Client/src/app/services/api/users.service.ts

SignalR url goes from config.json

SignalR url goes from config.json

---

.github/workflows/build-test-coverage-dotnet.yml
.github/workflows/qoudana-scan.yml
.github/workflows/resharper-scan.yml
MangoAPI.sln

Closes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/397

quodana and resharper scans

---

MangoAPI.Application/MangoAPI.Application.csproj
MangoAPI.Application/Services/AvatarService.cs
MangoAPI.BusinessLogic/Configuration/MangoStartup.cs
MangoAPI.BusinessLogic/MangoAPI.BusinessLogic.csproj
MangoAPI.DiffieHellmanLibrary/MangoAPI.DiffieHellmanLibrary.csproj
MangoAPI.Domain/MangoAPI.Domain.csproj
MangoAPI.Infrastructure/MangoAPI.Infrastructure.csproj
MangoAPI.IntegrationTests/MangoAPI.IntegrationTests.csproj
MangoAPI.Presentation/MangoAPI.Presentation.csproj
MangoAPI.Presentation/Startup.cs
MangoAPI.sln.DotSettings

Fixes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/388

Packages bump

---

MangoAPI.Client/src/app/components/chats/chats.component.html
MangoAPI.Client/src/app/components/chats/chats.component.ts
MangoAPI.Client/src/app/components/contacts/contacts.component.html
MangoAPI.Client/src/app/components/contacts/contacts.component.ts
MangoAPI.Client/src/app/components/navbar/navbar.component.html
MangoAPI.Client/src/app/components/settings/settings.component.html
MangoAPI.Client/src/app/components/settings/settings.component.ts
MangoAPI.Client/src/app/services/states/blackCoverState.service.ts
MangoAPI.Client/src/app/services/states/modalWindowState.service.ts
MangoAPI.Client/src/styles.scss

Fixes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/395

Add showing full size avatar frontend

---

MangoAPI.Client/src/app/interceptors/auth-interceptor.service.ts
MangoAPI.Client/src/app/interceptors/request-header.interceptor.ts

Fixes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/391

add redirect if refresh token is invalid

---

MangoAPI.BusinessLogic/ApiCommands/Users/RegisterCommand.cs
MangoAPI.BusinessLogic/ApiCommands/Users/RegisterCommandValidator.cs
MangoAPI.BusinessLogic/ApiCommands/Users/RegisterRequest.cs
MangoAPI.Client/src/app/components/register/register.component.html
MangoAPI.Client/src/app/components/register/register.component.ts
MangoAPI.Client/src/app/types/requests/RegisterCommand.ts
MangoAPI.IntegrationTests/Helpers/CommandHelper.cs

Fixes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/385

remove registration checkbox

---

MangoAPI.Client/src/app/components/chats/chats.component.html
MangoAPI.Client/src/app/components/chats/chats.component.ts
MangoAPI.Client/src/app/services/states/replyState.service.ts
MangoAPI.Client/src/app/types/models/Message.ts
MangoAPI.Client/src/app/types/models/Reply.ts
MangoAPI.Client/src/assets/svg/cross.svg
MangoAPI.Client/src/assets/svg/reply2.svg
MangoAPI.Client/src/styles.scss

Fixes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/387
Implements missing features

add reply and showing attachment pic

---

MangoAPI.Presentation/Controllers/ApiControllerBase.cs
MangoAPI.Presentation/Controllers/AppInfoController.cs
MangoAPI.Presentation/Controllers/CommunitiesController.cs
MangoAPI.Presentation/Controllers/ContactsController.cs
MangoAPI.Presentation/Controllers/KeyExchangeController.cs
MangoAPI.Presentation/Controllers/MessagesController.cs
MangoAPI.Presentation/Controllers/SessionsController.cs
MangoAPI.Presentation/Controllers/UserChatsController.cs
MangoAPI.Presentation/Controllers/UsersController.cs
MangoAPI.Presentation/Middlewares/ExceptionHandlingMiddleware.cs
MangoAPI.Presentation/Startup.cs

Fixes https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/384

Logging enabled in controller

---

MangoAPI.BusinessLogic/ApiCommands/Communities/CreateChatCommandHandler.cs
MangoAPI.BusinessLogic/ApiCommands/Messages/SendMessageCommand.cs
MangoAPI.BusinessLogic/ApiCommands/Messages/SendMessageCommandHandler.cs
MangoAPI.BusinessLogic/ApiCommands/Messages/SendMessageRequest.cs
MangoAPI.Client/src/app/components/chats/chats.component.ts
MangoAPI.Domain/Entities/MessageEntity.cs
MangoAPI.IntegrationTests/Helpers/CommandHelper.cs
MangoAPI.Presentation/Controllers/MessagesController.cs

Closes:
- https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/440
- https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/441

Update message submission flow

---

.github/workflows/build-angular.yml
.github/workflows/build-test-coverage-dotnet.yml
.github/workflows/qoudana-scan.yml
.github/workflows/resharper-scan.yml
MangoAPI.Client/src/app/components/settings/settings.component.html
MangoAPI.Client/src/app/components/settings/settings.component.ts
MangoAPI.Client/src/app/components/settings/settings.helper.ts
MangoAPI.Client/src/app/services/api/session.service.ts
MangoAPI.Client/src/app/services/api/users.service.ts
MangoAPI.Client/src/app/types/requests/UpdatePersonalInformationCommand.ts
MangoAPI.sln
build/azure-pipelines-cd.yml
build/azure-pipelines-ci.yml

Fixes: https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/428
- Unused code clean up
- Settings component works on promises
TODO:
- Return user model from `api/users/account`
- Return user model from `api/users/social`

Refactors in settings component

---

MangoAPI.Client/src/styles.scss

Fixes: https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/437

Smooth scroll

---

MangoAPI.BusinessLogic/ApiCommands/Users/UpdatePersonalInformationCommand.cs
MangoAPI.BusinessLogic/ApiCommands/Users/UpdatePersonalInformationCommandHandler.cs
MangoAPI.BusinessLogic/ApiCommands/Users/UpdatePersonalInformationResponse.cs
MangoAPI.BusinessLogic/ApiCommands/Users/UpdateUserAccountInfoCommand.cs
MangoAPI.BusinessLogic/ApiCommands/Users/UpdateUserAccountInfoCommandHandler.cs
MangoAPI.BusinessLogic/ApiCommands/Users/UpdateUserAccountInfoResponse.cs
MangoAPI.Client/src/app/components/settings/settings.component.html
MangoAPI.Client/src/app/components/settings/settings.component.ts
MangoAPI.Client/src/app/services/api/users.service.ts
MangoAPI.Client/src/app/types/responses/UpdatePersonalInformationResponse.ts
MangoAPI.Client/src/app/types/responses/UpdateUserAccountInfoResponse.ts
MangoAPI.IntegrationTests/ApiCommandsTests/UpdateUserAccountInfoCommandHandlerTests/UpdateUserAccountInfoTestShouldThrowUserNotFound.cs
MangoAPI.IntegrationTests/ApiCommandsTests/UpdateUserAccountInfoCommandHandlerTests/UpdateUserAccountInfoTestSuccess.cs
MangoAPI.IntegrationTests/ApiCommandsTests/UpdateUserSocialsInformationCommandHandlerTests/UpdatePersonalInformationTestShouldThrowUserNotFound.cs
MangoAPI.IntegrationTests/ApiCommandsTests/UpdateUserSocialsInformationCommandHandlerTests/UpdatePersonalInformationTestSuccess.cs
MangoAPI.sln.DotSettings

Fixes: https://github.com/MangoInstantMessenger/MangoMessengerAPI/issues/445

Settings bugfix

---

CHANGELOG.md

Prepare release v0.2.1
